swagger: '2.0'

info:
  version: "0.1"
  title: Web API for Tire Control Software 

paths:

  /signup:
    post:
      description: Create user in the API

      parameters:
        - name: name
          in: formData
          description: User name
          required: true
          type: string
        - name: username
          in: formData
          description: Username (user login)
          required: true
          type: string
        - name: email
          in: formData
          description: User email
          required: true
          type: string
        - name: passwd
          in: formData
          description: User password
          required: true
          type: string
          format: password

      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/Signup'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'


  /login:
    post:
      description: Login to the API and GET token

      parameters:
        - name: email
          in: formData
          description: User email
          required: true
          type: string
        - name: passwd
          in: formData
          description: User password
          required: true
          type: string
          format: password

      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/Login'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

  /logout:
    put:
      description: Logout from Web API using token

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string

      responses:
        204:
          description: No Content
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

  /tires/brand:
    get:
      description: Get tire brands

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string

      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/TireBrand'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

    post:
      description: Register tire brand

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string
        - name: name
          in: formData
          description: The tire brand name
          required: true
          type: string

      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/TireBrand'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

  /tires/model:
    get:
      description: Get tire models

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string

      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/TireModel'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

    post:
      description: Register tire model

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string
        - name: name
          in: formData
          description: The tire model name
          required: true
          type: string

      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/TireModel'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

  /tires/size:
    get:
      description: Get tire sizes

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string

      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/TireSize'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

    post:
      description: Register tire size

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string
        - name: name
          in: formData
          description: The tire size name
          required: true
          type: string

      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/TireSize'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError' 

  /tires/type:
    get:
      description: Get tire types

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string

      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/TireType'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

    post:
      description: Register tire type

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string
        - name: name
          in: formData
          description: The tire type name
          required: true
          type: string

      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/TireType'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'      

definitions:

  Signup:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      email:
        type: string
      username:
        type: string

  Login:
    type: object
    properties:
      user_name:
        type: string
      user_email:
        type: string
      token:
        type: string

  TireBrand:
    type: object
    properties:
      id:
        type: string
      name:
        type: string

  TireModel:
    type: object
    properties:
      id:
        type: string
      name:
        type: string

  TireSize:
    type: object
    properties:
      id:
        type: string
      name:
        type: string

  TireType:
    type: object
    properties:
      id:
        type: string
      name:
        type: string

  ApiError:
    type: object
    properties:
      error:
        type: string
      errors:
        type: array
        items:
          type: string