swagger: '2.0'

info:
  version: "0.1"
  title: Web API for Tire Control Software 

paths:

  /signup:
    post:
      description: Create user in the API
      produces: 
      - application/json
      consumes: 
      - application/x-www-form-urlencoded
      - application/json

      parameters:
        - name: name
          in: formData
          description: User name
          required: true
          type: string
        - name: username
          in: formData
          description: Username (user login)
          required: true
          type: string
        - name: email
          in: formData
          description: User email
          required: true
          type: string
        - name: passwd
          in: formData
          description: User password
          required: true
          type: string
          format: password

      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/Signup'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'


  /login:
    post:
      description: Login to the API and GET token
      produces: 
      - application/json
      consumes: 
      - application/x-www-form-urlencoded
      - application/json

      parameters:
        - name: email
          in: formData
          description: User email
          required: true
          type: string
        - name: passwd
          in: formData
          description: User password
          required: true
          type: string
          format: password

      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/Login'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

  /logout:
    put:
      description: Logout from Web API using token

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string

      responses:
        204:
          description: No Content
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

  /tires/brands:
    get:
      description: Get tire brands

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string

      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/Tire'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

    post:
      description: Register tire brand
      produces: 
      - application/json
      consumes: 
      - application/x-www-form-urlencoded
      - application/json

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string
        - name: name
          in: formData
          description: The tire brand name
          required: true
          type: string

      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/Tire'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

  /tires/models:
    get:
      description: Get tire models

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string

      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/Tire'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

    post:
      description: Register tire model
      produces: 
      - application/json
      consumes: 
      - application/x-www-form-urlencoded
      - application/json

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string
        - name: name
          in: formData
          description: The tire model name
          required: true
          type: string

      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/Tire'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

  /tires/sizes:
    get:
      description: Get tire sizes

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string

      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/Tire'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

    post:
      description: Register tire size
      produces: 
      - application/json
      consumes: 
      - application/x-www-form-urlencoded
      - application/json

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string
        - name: name
          in: formData
          description: The tire size name
          required: true
          type: string

      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/Tire'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError' 

  /tires/types:
    get:
      description: Get tire types

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string

      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/Tire'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

    post:
      description: Register tire type
      produces: 
      - application/json
      consumes: 
      - application/x-www-form-urlencoded
      - application/json

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string
        - name: name
          in: formData
          description: The tire type name
          required: true
          type: string

      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/Tire'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'      

  /tires:
    get:
      description: Get tires

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string

      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/TireFull'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

    post:
      description: Register tire
      produces: 
      - application/json
      consumes: 
      - application/x-www-form-urlencoded
      - application/json

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string
        - name: brand
          in: formData
          description: The tire brand name
          required: true
          type: string
        - name: model
          in: formData
          description: The tire model name
          required: true
          type: string
        - name: size
          in: formData
          description: The tire size name
          required: true
          type: string
        - name: type
          in: formData
          description: The tire type name
          required: true
          type: string
        - name: dot
          in: formData
          description: The tire dot
          required: true
          type: string
        - name: code
          in: formData
          description: The tire code/identification
          required: true
          type: string

      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/TireFull'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError' 

  /vehicles/brands:
    get:
      description: Get vehicle brands

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string

      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/Vehicle'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

    post:
      description: Register vehicle brand
      produces: 
      - application/json
      consumes: 
      - application/x-www-form-urlencoded
      - application/json

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string
        - name: name
          in: formData
          description: The vehicle brand name
          required: true
          type: string

      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/Vehicle'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

  /vehicles/categories:
    get:
      description: Get vehicle categories

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string

      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/Vehicle'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

    post:
      description: Register vehicle category
      produces: 
      - application/json
      consumes: 
      - application/x-www-form-urlencoded
      - application/json

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string
        - name: name
          in: formData
          description: The vehicle category name
          required: true
          type: string

      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/Vehicle'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError' 

  /vehicles/models:
    get:
      description: Get vehicle models

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string

      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/VehicleModel'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

    post:
      description: Register vehicle model
      produces: 
      - application/json
      consumes: 
      - application/x-www-form-urlencoded
      - application/json

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string
        - name: brand
          in: formData
          description: The vehicle brand name
          required: true
          type: string
        - name: model
          in: formData
          description: The vehicle model name
          required: true
          type: string

      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/VehicleModel'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'  

  /vehicles/types:
    get:
      description: Get vehicle types

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string

      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/Vehicle'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

    post:
      description: Register vehicle type
      produces: 
      - application/json
      consumes: 
      - application/x-www-form-urlencoded
      - application/json

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string
        - name: name
          in: formData
          description: The vehicle type name
          required: true
          type: string

      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/Vehicle'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'      

  /vehicles:
    get:
      description: Get vehicles

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string

      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/Vehicle'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

    post:
      description: Register vehicle
      produces: 
      - application/json
      consumes: 
      - application/x-www-form-urlencoded
      - application/json

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string
        - name: brand
          in: formData
          description: The vehicle brand name
          required: true
          type: string
        - name: category
          in: formData
          description: The vehicle category name
          required: true
          type: string
        - name: model
          in: formData
          description: The vehicle model name
          required: true
          type: string
        - name: type
          in: formData
          description: The vehicle type name
          required: true
          type: string
        - name: plate
          in: formData
          description: The vehicle plate
          required: true
          type: string

      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/VehicleFull'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError' 

definitions:

  Signup:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      email:
        type: string
      username:
        type: string

  Login:
    type: object
    properties:
      user_name:
        type: string
      user_email:
        type: string
      token:
        type: string

  Tire:
    type: object
    properties:
      id:
        type: string
      name:
        type: string

  TireFull:
    type: object
    properties:
      id:
        type: string
      brand:
        type: string
      model:
        type: string
      size:
        type: string
      type:
        type: string
      dot:
        type: string
      code:
        type: string

  Vehicle:
    type: object
    properties:
      id:
        type: string
      name:
        type: string

  VehicleModel:
    type: object
    properties:
      id:
        type: string
      brand:
        type: string
      model:
        type: string

  VehicleFull:
    type: object
    properties:
      id:
        type: string
      brand:
        type: string
      category:
        type: string
      model:
        type: string
      type:
        type: string
      plate:
        type: string
      
  ApiError:
    type: object
    properties:
      error:
        type: string
      errors:
        type: array
        items:
          type: string