swagger: '2.0'

info:
  version: "0.1"
  title: Web API for Tire Control Software 

paths:

  /signup:
    post:
      description: Create user in the API

      parameters:
        - name: name
          in: formData
          description: User name
          required: true
          type: string
        - name: username
          in: formData
          description: Username (user login)
          required: true
          type: string
        - name: email
          in: formData
          description: User email
          required: true
          type: string
        - name: passwd
          in: formData
          description: User password
          required: true
          type: string
          format: password

      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/Signup'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'


  /login:
    post:
      description: Login to the API and GET token

      parameters:
        - name: email
          in: formData
          description: User email
          required: true
          type: string
        - name: passwd
          in: formData
          description: User password
          required: true
          type: string
          format: password

      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/Login'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

  /logout:
    put:
      description: Logout from Web API using token

      parameters:
        - name: token
          in: header
          description: The Web API Token
          required: true
          type: string

      responses:
        204:
          description: No Content
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/ApiError'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

definitions:

  Signup:
    type: object
    properties:
      name:
        type: string
      email:
        type: string
      username:
        type: string

  Login:
    type: object
    properties:
      user_name:
        type: string
      user_email:
        type: string
      token:
        type: string

  ApiError:
    type: object
    properties:
      error:
        type: string
      errors:
        type: array
        items:
          type: string